services:
  dev-db:
    image: postgres:16.3
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket-service
    networks:
      - nestjs

networks:
  nestjs:
